services:
    sonata.admin.capacity:
        class: FormGeneratorBundle\Admin\CapacityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Compétence", label: "Capacité" }
        arguments:
            - ~
            - FormGeneratorBundle\Entity\Capacity
            - ~
        calls:
            - [ setTranslationDomain, [FomrGeneratorBundle]]
    sonata.admin.stateSkill:
        class: FormGeneratorBundle\Admin\SkillStateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Compétence", label: "Statut d'une compétence" }
        arguments:
            - ~
            - FormGeneratorBundle\Entity\SkillState
            - ~
        calls:
            - [ setTranslationDomain, [FormGeneratorBundle]]

    sonata.admin.status:
        class: FormGeneratorBundle\Admin\StatusAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Suivi des fiches", label: "Statut de fiche" }
        arguments:
            - ~
            - FormGeneratorBundle\Entity\Status
            - ~
        calls:
            - [ setTranslationDomain, [FormGeneratorBundle]]

    sonata.admin.condition:
        class: FormGeneratorBundle\Admin\ConditionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "ConditionsMeet de travail", label: "ConditionsMeet" }
        arguments:
            - ~
            - FormGeneratorBundle\Entity\Condition
            - ~
        calls:
            - [ setTranslationDomain, [FormGeneratorBundle]]