services:
    app.customfields_parser:
        class:        FormGeneratorBundle\Service\CustomFieldsParser
        arguments: ['@kernel']
    app.prepopulate_entity:
        class:        FormGeneratorBundle\Service\PrePopulateEntity
        arguments: ['@form.factory', '@router', '@doctrine.orm.default_entity_manager'] #['@service_container', '@form.factory', '@router']

    app_main.menu_builder:
        class: FormGeneratorBundle\Menu\Builder
    app_main.menu.main:
        class: KnpMenuMenuItem
        factory_service: app_main.menu_builder
        factory_method: mainMenu
        arguments: ["@knp_menu.factory", "@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main } # L'alias est très important, c'est avec lui que vous appellerez votre menu dans la vue

#    app.voter.request:
#        class: FormGeneratorBundle\Service\Voter\RequestVoter
#        arguments:
#            - ["@service_container"]
#        tags:
#            - { name: knp_menu.voter }
