imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata.yml }
#    - { resource: '@FormGeneratorBundle/Resources/config/services.yml' }
    - { resource: '@AppBundle/Resources/config/admin.yml' }
    - { resource: '@UserBundle/Resources/config/services.yml' }
    - { resource: '@AppBundle/Resources/config/services.yml' }
    - { resource: '@GeneratorBundle/Resources/config/services.yml' }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    assetic.filter.compass.images_dir: %kernel.root_dir%/../web/img
    assetic.filter.compass.http_path:  /img

framework:
    #esi:             ~
    translator: { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.root_dir%/../app/Resources/FOSUserBundle/views": custom_fos
        "%kernel.root_dir%/../app/Resources/ArianespacePlexcelBundle/Resources/views": custom_plexcel
    form:
        resources:
           - "GeneratorBundle:Form:form_fields.html.twig"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles: [UserBundle, GeneratorBundle, FOSUserBundle, AppBundle, ArianespaceThemeBundle]
    filters:
        cssrewrite: ~
        less:
            node:       /usr/bin/node
            node_paths: [/usr/lib/node_modules]
            apply_to:   "\.less$"
        sass:
            bin: /usr/local/bin/sass
        compass:
            bin: /usr/local/bin/compass
    assets:
        data_tables:
            inputs:
                - %kernel.root_dir%/../web/vendor/datatables/media/js/jquery.dataTables.min.js

braincrafted_bootstrap:
    less_filter: less
# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            generator:
                driver:   pdo_pgsql #pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            old:
                driver:   pdo_pgsql #pdo_mysql
                host:     "%database_host_old%"
                port:     "%database_port_old%"
                dbname:   "%database_name_old%"
                user:     "%database_user_old%"
                password: "%database_password_old%"
                charset:  UTF8
            default:
                driver:   pdo_pgsql #pdo_mysql
                host:     "%database_host_3%"
                port:     "%database_port_3%"
                dbname:   "%database_name_3%"
                user:     "%database_user_3%"
                password: "%database_password_3%"
                charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        default_entity_manager:   default
        auto_generate_proxy_classes: "%kernel.debug%"
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        #auto_mapping: true
        entity_managers:
            default:
                connection:       default
                mappings:
                    FormGeneratorBundle: ~
                    UserBundle: ~
                    FOSUserBundle: ~
                    ArianespacePlexcelBundle: ~
                    GeneratorBundle: ~
                  #  SonataMediaBundle: ~
            old:
                connection: old
                mappings:
                    OldOpusBundle: ~
            generator:
                connection: generator
                mappings:
                    GeneratorBundle: ~
                    UserBundle: ~
                    AppBundle: ~
                    ArianespacePlexcelBundle: ~
                    FormGeneratorBundle: ~
#    dbal:
#        types:
#            json: Sonata\Doctrine\Types\JsonType



# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

genemu_form:
    tinymce:
        enabled: true
        theme: modern
        configs:
            entity_encoding: raw
            plugins : 'advlist autolink link image lists charmap print preview'

    date: ~
    image: ~
    select2: ~
    autocomplete: ~
    date: ~
#        enabled: true
#        configs:
#            placeholder: Sélectionner
#            width: off
#            allowClear: false
#            minimumInputLength: 0


arianespace_plexcel:
    enable:               true
    autologin:            false
    local:                true
    create:               true
    application:
#        name:                 "%application.name%"
#        version:              "%application.version%"
#        description:          "%application.description%"
    auto_add_domain:     ad.arianespace.fr
    autologin_redirect_route:  homepage
    check_plexcel_login:  true
    check_plexcel_redirect_route:  homepage
    authorized_cn:
        'CN=opus_appraisees_pilot,OU=Opus,OU=SI,DC=ad,DC=arianespace,DC=fr': 'ROLE_USER'
    user_manager:         user_manager
    file:                 "%kernel.root_dir%/../plexcel/plexcel.php"