old_opus:
    resource: "@OldOpusBundle/Controller/"
    type:     annotation
    prefix:   /

formgenerator:
    resource: "@FormGeneratorBundle/Controller/"
    type:     annotation

generator:
    resource: "@GeneratorBundle/Resources/config/routing.yml"


app:
    resource: "@AppBundle/Controller/"
    type:     annotation

opus_user:
    resource: "@UserBundle/Resources/config/routing.yml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

plexcel_bundle:
    resource: "@ArianespacePlexcelBundle/Resources/config/routing.yml"

sso:
    resource: "@ArianespacePlexcelBundle/Resources/config/routing.yml"

login:
    resource: "@UserBundle/Resources/config/routing.yml"
