generator:
    resource: "@GeneratorBundle/Resources/config/routing.yml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

opus_user:
    resource: "@UserBundle/Resources/config/routing.yml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

plexcel_bundle:
    resource: "@ArianespacePlexcelBundle/Resources/config/routing.yml"

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

sso:
    resource: "@ArianespacePlexcelBundle/Resources/config/routing.yml"

login:
    resource: "@UserBundle/Resources/config/routing.yml"


#gallery:
#    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
#    prefix: /media/gallery
#
#media:
#    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
#    prefix: /media

arianespace_theme_bundle_home:
    path: /_arianespace/themebundle/home
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ArianespaceThemeBundle:Example:home.html.twig'

arianespace_theme_bundle_form:
    path: /_arianespace/themebundle/form
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ArianespaceThemeBundle:Example:form.html.twig'

arianespace_theme_bundle_table:
    path: /_arianespace/themebundle/table
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ArianespaceThemeBundle:Example:table.html.twig'

arianespace_theme_bundle_login:
    path: /_arianespace/themebundle/login
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ArianespaceThemeBundle:Example:login.html.twig'

