security:
    encoders:
        UserBundle\Entity\User: sha512
        #FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User:      sha512
        Arianespace\MopBundle\Entity\User: sha512

    providers:
        plexcel_provider:
            id: user_provider
        in_memory:
            memory:
                users:
                    lody: { password: test, roles: 'ROLE_USER' }
        chain_provider:
            chain :
                providers: [plexcel_provider, in_memory]


#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            switch_user: true
        login:
            pattern:  ^/(login|try_sso)$
            security: false
            switch_user: true
        secured_area:
            pattern:    ^/
            plexcel: true
            form_login:
                login_path:  /login
                check_path:  /login_check
                provider:    chain_provider
            logout:
                path:    /logout
                invalidate_session: false
                handlers:           [ arianespace.plexcel.logout_handler ]
            switch_user: true
            anonymous:    true
#        main:
#            #provider: fos_userbundle #custom_user
#            pattern: ^.*$
##            plexcel:
##              always_use_default_target_path: true
##              default_target_path: /start
#            form_login:
#                check_path: /login_check
#                login_path: /login
#                provider: fos_userbundle
#            logout:
#                handlers: [arianespace.plexcel.logout_handler]

    access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/try_sso, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }
            - { path: ^/, role: [ROLE_USER]}
#            - { path: /login*, role: IS_AUTHENTICATED_ANONYMOUSLY }
#            - { path: .*, role: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_ADMIN:             [ROLE_USER,ROLE_DIRECTOR,ROLE_RH,ROLE_DIVISION_MANAGER,ROLE_MANAGER]
        ROLE_DIRECTOR:          [ROLE_USER]
        ROLE_RH:                [ROLE_USER]
        ROLE_DIVISION_MANAGER:  [ROLE_USER]
        ROLE_MANAGER:           [ROLE_USER]
        ROLE_USER: [ROLE_ALLOWED_TO_SWITCH]


#        secured_area:
#            pattern:    ^/
#            plexcel: true
#            form_login:
#                provider: fos_userbundle
#            logout:
#                path:               /logout
#                invalidate_session: false
#                handlers:           [ arianespace.plexcel.logout_handler ]
#                target: /login
#            anonymous:    true
