security:
    encoders:
        #UserBundle\Entity\User: sha512
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_provider.username


    firewalls:
       admin:
           pattern: admin/
           form_login:
               check_path: /admin/login_check
               login_path: /login
               provider: fos_userbundle
           logout:
               path:    /logout
               target: /
           anonymous:    true
       secured_area:
           pattern:    ^/
           plexcel: true
           form_login:
               provider: fos_userbundle
           logout:
               path:    /logout
               invalidate_session: false
               handlers:           [ arianespace.plexcel.logout_handler ]
               target: /login
           anonymous:    true
       main:
           pattern: ^/
           form_login:
               check_path: /login_check
               login_path: /login
               provider: fos_userbundle
           logout:
               path:    /logout
               target: /login
           anonymous:    true
       dev:
           pattern: ^/(_(profiler|wdt|error)|css|images|js)/
           security: false
           anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/try_sso, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
#        - { path: ^/valuation/^, role: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/, role: [ROLE_ADMIN, ROLE_USER]}
