name: "Entretien sur les conditions de travail"
id: "conditions_meet"
fields:
    attr:
        - id: "cond_workconditions"
          type: "collection"
          export_name: "Conditions de travail"
          export_desc: "Liste des évaluations des conditions de travail"
          export_value: null
          conf:
              allow_add: true
              type: "to defined"
              allow_delete: true
              by_reference: false
              required: false
              label: "Le salarié est-il satisfait de :"
              attr:
                  data-tab: "tab_2"
                  data-access: "evaluator"
          child:
              - id: "cond_workconditions_name"
                type: "textarea"
                conf:
                    label: "Conditions"
                    required: false
                    attr:
                        data-tab: "tab_2"
                        readonly: true
              - id: "cond_workconditions_evaluation"
                type: "choice"
                conf:
                    label: "Note"
                    choices: { 1: "1", 2: "2", 3: "3", 4: "4", 0: "Pas d'avis"}
                    required: true
                    expanded: true
                    multiple: false
                    attr:
                        data-tab: "tab_2"
              - id: "cond_workconditions_comments"
                type: "textarea"
                conf:
                    label: "Commentaire(s)"
                    required: false
                    attr:
                        class: "textarea-resize no-horizontal"
                        data-tab: "tab_2"
          number: 10
          predefined_values:
              cond_workconditions_name: [ "Sa charge de travail", "L’amplitude de ses journées de travail", "L’organisation et répartition de la charge de travail dans l’équipe/dans l’entreprise", "L’articulation vie professionnelle/ vie privée", "Sa rémunération", "Ses conditions de travail", "Ses relations avec l’équipe (soutien, entraide)", "Ses relations avec ses clients/fournisseurs", "Ses relations avec sa hiérarchie", "La communication interne (dans l’équipe, dans l’entreprise)" ]

        - id: "emp_comm_conditions"
          type: "textarea"
          conf:
              label: "Commentaires du salarié – propositions d’amélioration  :"
              required: false
              attr:
                  data-tab: "tab_3"
                  data-access: "evaluate"
                  class: "textarea-resize no-horizontal"
tabs_ui:
    - id: "tab_1"
      name: "Général"
    - id: "tab_2"
      name: "Evaluation"
    - id: "tab_3"
      name: "Impression évalué"



