name: "Entretien sur les conditions de travail"
id: "conditions_meet"
fields:
    attr:
        - id: "emp_comm_conditions"
          type: "genemu_tinymce"
          conf:
              label: "Commentaires du salarié – propositions d’amélioration  :"
              required: false
              attr:
                  data-tab: 'tab_1'