id: "pro_meet"
name: "Entretien professionel"
fields:
    attr:
        - id: "professional_temp"
          type: "collection"
          conf:
              allow_add: true
              type: "to defined"
              allow_delete: true
              by_reference: false
              required: false
              label: "Précisez dans quel cadre a eu lieu l'entretien.<br> Entretien professionnel :"
              attr:
                  data-tab: 'tab_1'
          child:
              - id: "temp_choice"
                type: "choice"
                conf:
                    required: true
                    choices: { annual: "annuel", parent: "à l'issue d'un congé lié à la parentalité", duration: "à l'issue d’un arrêt de longue durée ", sabbatique: "à l'issue d’un congé sabbatique ", mobility: "à l'issue d’un période de mobilité volontaire sécurisée ", mandat: "à l'issue d’un mandat syndical ou représentatif" }
                    expanded: true
                    multiple: false
                    label: 'Préciser dans quel cadre l’entretien a lieu' #Norme W3C : mieux vaut <th> vide que rien
                    attr:
                        data-tab: 'tab_1'
                        class: "col-md-2"
          number: 1
        - id: "professional_skills"
          type: "collection"
          conf:
              allow_add: true
              type: "to defined"
              allow_delete: true
              by_reference: false
              required: false
              label: "Quels sont les points forts du salarié, sa valeur ajoutée dans l'équipe ?"
              attr:
                  data-tab: 'tab_2'
          child:
              - id: "skills_text"
                type: "text"
                conf:
                    label: "Compétences métier (savoir/savoir-faire) ou aptitudes particulières"
                    required: false
                    attr:
                        data-tab: 'tab_2'
              - id: "skills_comment"
                type: "textarea"
                conf:
                    label: "Commentaire/Illustration"
                    required: false
                    attr:
                        data-tab: 'tab_2'
          number: 5
        - id: "condition_bool"
          type: "checkbox"
          conf:
              label: "Le salarié détient une <i>compétence rare ou unique</i> nécessaire au bon fonctionnement de l’entreprise : "
              required: false
              attr:
                 data-tab: 'tab_2'
        - id: "professional_skill"
          type: "collection"
          conf:
              allow_add: true
              type: "to defined"
              allow_delete: true
              by_reference: false
              required: false
              label: false
              attr:
                  data-tab: 'tab_2'
          child:
              - id: "skill_text"
                type: "text"
                conf:
                    label: "Compétences "
                    required: false
                    attr:
                        data-tab: 'tab_2'
              - id: "skill_comment"
                type: "textarea"
                conf:
                    label: "Comment envisagez-vous la transmission ou le partage de cette compétence ?"
                    required: false
                    attr:
                        data-tab: 'tab_2'
          number: 5
        - id: "professional_improve"
          type: "collection"
          conf:
              allow_add: true
              type: "to defined"
              allow_delete: true
              by_reference: false
              required: false
              label: "Quels sont les points à améliorer ?"
              attr:
                  data-tab: 'tab_2'
          child:
              - id: "improve_text"
                type: "text"
                conf:
                    label: "Aptitude, savoir, savoir-faire, comportement, Etc. "
                    required: false
                    attr:
                        data-tab: 'tab_2'
              - id: "improve_comment"
                type: "textarea"
                conf:
                    label: "Commentaires/ illustration"
                    required: false
                    attr:
                        data-tab: 'tab_2'
          number: 5
        - id: "professional_evolution"
          type: "textarea"
          conf:
              label: "Evolutions prévisibles, à court et moyen terme, dans l’emploi du salarié, dans le service ou l’entreprise (évolutions d’organisation, techniques, technologiques, évolution de la charge de service, départs à la retraite, recrutements à venir, nouveaux projets …) :"
              required: false
              attr:
                  data-tab: "tab_3"
        - id: "professional_goals"
          type: "textarea"
          conf:
              label: "<i>Objectifs de professionnalisation du salarié </i>: Evolutions souhaitées dans le poste, dans l’entreprise ou autre projet professionnel  à court ou moyen terme :"
              required: false
              attr:
                  data-tab: "tab_3"
        - id: "professional_mobility_bool"
          type: "checkbox"
          conf:
              label: "Le salarié est mobile géographiquement :"
              required: false
              attr:
                  data-tab: "tab_3"
        - id: "professional_mobility_site"
          type: "collection"
          conf:
              allow_add: true
              type: "to defined"
              allow_delete: true
              by_reference: false
              required: false
              label: "Si oui vers quel(s) site(s) et à quelle échéance ?"
              attr:
                  data-tab: 'tab_3'
          child:
              - id: "improve_text"
                type: "text"
                conf:
                    label: "Site"
                    required: false
                    attr:
                        data-tab: 'tab_3'
              - id: "improve_comment"
                type: "genemu_jquerydate"
                conf:
                    label: "Echéance"
                    required: false
                    attr:
                        data-tab: 'tab_3'
                        class: 'datepicker'
                    widget: 'single_text'
                    format: 'dd/MM/yyyy'
          number: 5
        - id: "professional_review"
          type: 'textarea'
          conf:
              label: "Avis de l’évaluateur sur ces objectifs de professionnalisation (atouts/ freins, possibilités,…):"
              required: false
              attr:
                  data-tab: "tab_3"
        - id: "professional_prof_evolution"
          type: "checkbox"
          conf:
              label: "Le salarié souhaite un entretien spécifique pour discuter de son évolution professionnelle avec la DRH"
              required: false
              attr:
                  data-tab: "tab_3"
# TAB 4
        - id: "training_desired_actions"
          type: "collection"
          conf:
              allow_add: true
              type: "to defined"
              allow_delete: true
              by_reference: false
              required: false
              label: "Actions de formations souhaitées (pour mener sa mission, réaliser ses objectifs, s’adapter aux évolutions prévisibles ou pour atteindre les objectifs de professionnalisation envisagés)"
              attr:
                  data-tab: 'tab_4'
          child:
              - id: "training_desired_actions_skill_to_develop"
                type: "textarea"
                conf:
                    label: "Compétence à développer"
                    required: false
                    attr:
                        data-tab: 'tab_4'
              - id: "training_desired_actions_result_achieved"
                type: "textarea"
                conf:
                    label: "Résultat à atteindre"
                    required: false
                    attr:
                        data-tab: 'tab_4'
              - id: "training_desired_actions_training_planned"
                type: "textarea"
                conf:
                    label: "Stage envisagéé"
                    required: false
                    attr:
                        data-tab: 'tab_4'
              - id: "training_desired_actions_organism"
                type: "textarea"
                conf:
                    label: "Organisme"
                    required: false
                    attr:
                        data-tab: 'tab_4'
              - id: "training_desired_desired_period"
                type: "textarea"
                conf:
                    label: "Période souhaitée"
                    required: false
                    attr:
                        data-tab: 'tab_4'
              - id: "training_desired_priority"
                type: "textarea"
                conf:
                    label: "Priorité"
                    required: false
                    attr:
                        data-tab: 'tab_4'
              - id: "training_desired_motive"
                type: "choice"
                conf:
                    label: "Motif"
                    choices: { 0: "Adaptation au poste", 1: "Evolution du poste", 2: "Changement de poste", 3: "Employabilité"}
                    expanded: true
                    multiple: false
                    required: true
                    data: 0
                    attr:
                        data-tab: "tab_4"
          number: 5
        - id: "last_training_followed"
          type: "collection"
          conf:
              allow_add: true
              type: "to defined"
              allow_delete: true
              by_reference: false
              required: false
              label: "Evaluation des dernières formations suivies"
              attr:
                  data-tab: 'tab_4'
          child:
              - id: "last_training_followed_internship"
                type: "text"
                conf:
                    label: "Libellé du stage"
                    required: false
                    attr:
                        data-tab: 'tab_4'
              - id: "last_training_followed_dates"
                type: "genemu_jquerydate"   
                conf:
                    label: "Dates"
                    required: false
                    attr:
                        data-tab: 'tab_4'
                        class: 'datepicker'
                    widget: 'single_text'
                    format: 'dd/MM/yyyy'
              - id: "last_training_followed_duration"
                type: "text"
                conf:
                    label: "Durée"
                    required: false
                    attr:
                        data-tab: 'tab_4'
              - id: "last_training_followed_hours_worked"
                type: "text"
                conf:
                    label: "Heures réalisées"
                    required: false
                    attr:
                        data-tab: 'tab_4'
              - id: "last_training_followed_target_skills"
                type: "textarea"
                conf:
                    label: "Compétences visées"
                    required: false
                    attr:
                        data-tab: 'tab_4'
              - id: "last_training_followed_practice"
                type: "textarea"
                conf:
                    label: "La formation a-t-elle été mise en pratique (illustrer)"
                    required: false
                    attr:
                        data-tab: 'tab_4'
              - id: "last_training_followed_judgment"
                type: "textarea"
                conf:
                    label: "Avis de l’évaluateur et de l’évalué sur la pertinence de cette formation"
                    required: false
                    attr:
                        data-tab: 'tab_4'
          number: 5
# TAB 5
        - id: "comments"
          type: "textarea"
          conf:
              label: "Commentaires ou précisions du salarié"
              required: false
              attr:
                  data-tab: "tab_5"
                  data-access: "evaluate"
tabs_ui:
    - id: 'tab_1'
      name: 'Général'
    - id: 'tab_2'
      name: "Compétences"
    - id: 'tab_3'
      name: "Evolutions"
    - id: 'tab_4'
      name: "Formations"
    - id: 'tab_5'
      name: "Commentaires"