name: "Entretien professionel"
id: "valuation_meet"
fields:
    attr:
        - id: "valuation_date"
          type: "date"
          conf:
              label: "Date de l'entretien :"
              required: false
        - id: "valuation_bool"
          type: "checkbox"
          conf:
              label: "L’année a-t-elle été marquée par un événement significatif (mutation, évolution importante des responsabilités, absence de longue durée, Etc) ?"
              required: false
        - id: "valuation_text"
          type: 'genemu_tinymce'
          conf:
              label: "Si oui, préciser l’événement et le contexte : "
              required: false
#        - id: "valuation_datetime"
#          type: "datetime"
#          conf:
#              label: "Saisissez une date et une heure"
#              required: false
#              attr:
#                  class: 'custom-time'
#        - id: "valuation_choice"
#          type: "choice"
#          conf:
#              label: "Genre"
#              required: true
#              choices: { m: "Masculin", f: "Féminin" }
#              expanded: true
#              multiple: false
#        - id: "valuation_city"
#          type: "entity"
#          conf:
#              label: "Sélectionnez une ville :"
#              required: true
#              class: "FormGeneratorBundle:City"
#              data_class: "FormGeneratorBundle\Entity\City"
#              property: "name"
#              expanded: true
#              multiple: false
#              attr:
#                  class: 'select-select2'
#        - id: "valuation_cities"
#          type: "entity"
#          conf:
#              label: "Sélectionnez une/plusieurs ville :"
#              required: false
#              class: "FormGeneratorBundle:City"
#              data_class: null
#              choice_label: "name"
#              expanded: true
#              multiple: true
        - id: "valuation_missions"
          type: collection
          conf:
              allow_add: true
              type: "to defined"
              allow_delete: true
              by_reference: false
              required: false
              label: "Saisissez des objectifs ci-dessous :"
          child:
              - id: "theme_text"
                type: "text"
                conf:
                    label: "Thème de la mission permanente"
                    required: false
              - id: "valuation_choice"
                type: "choice"
                conf:
                    label: "Etat"
                    required: true
                    choices: { n: "N", p: "P", r: "R", d: "D" }
                    expanded: true
                    multiple: false
              - id: "valuation_text"
                type: 'textarea'
                conf:
                    label: "Commentaires "
                    required: false
          number: 5
#        - id: "valuation_goals"
#          type: collection
#          conf:
#              allow_add: true
#              type: "to defined"
#              allow_delete: true
#              by_reference: false
#              required: false
#              label: "Saisissez des objectifs ci-dessous :"
#          child:
#              - id: "review_text"
#                type: "text"
#                conf:
#                    label: "Rappel des objectifs"
#                    required: false
#              - id: "metric_int"
#                type: "number"
#                conf:
#                    label: "Indicateur de mesure"
#                    required: false
#              - id: "valuation_city2"
#                type: "entity"
#                conf:
#                    label: "Sélectionnez une ville :"
#                    required: false
#                    class: "FormGeneratorBundle:City"
#                    data_class: "FormGeneratorBundle\Entity\City"
#                    choice_label: "name"
#                    expanded: true
#                    multiple: false
#                    label_attr:
#                        class: 'radio-inline'
#              - id: "review_text2"
#                type: "text"
#                conf:
#                    label: "Label 4"
#                    required: false
#              - id: "metric_int2"
#                type: "number"
#                conf:
#                    label: "Label 5"
#                    required: false
#              - id: "valuation_city22"
#                type: "entity"
#                conf:
#                    label: "Label 6 :"
#                    required: false
#                    class: "FormGeneratorBundle:City"
#                    data_class: "FormGeneratorBundle\Entity\City"
#                    choice_label: "name"
#                    expanded: true
#                    multiple: false
#              - id: "metric_int3"
#                type: "number"
#                conf:
#                    label: "Label 7"
#                    required: false
#          number: 2
#        - id: "valuation_skill"
#          type: collection
#          conf:
#              allow_add: true
#              type: "to defined"
#              allow_delete: true
#              by_reference: false
#              required: false
#              label: "Entrez vos compétences :"
#          child:
#              - id: "review_text"
#                type: "text"
#                conf:
#                    label: "Compétence :"
#                    required: false
#              - id: "metric_int"
#                type: "number"
#                conf:
#                    label: "Niveau"
#                    required: false
#          number: 2






