name: "Entretien d'appréciation"
id: "valuation_meet"
fields:
    attr:
        - id: "valuation_date"
          type: "genemu_jquerydate"
          conf:
              label: "Date de l'entretien :"
              required: false
              attr:
                  class: 'datepicker'
              widget: 'single_text'
              format: 'dd/MM/yyyy'
        - id: "valuation_bool"
          type: "checkbox"
          conf:
              label: "L’année a-t-elle été marquée par un événement significatif (mutation, évolution importante des responsabilités, absence de longue durée, Etc) ?"
              required: false
        - id: "valuation_text"
          type: 'genemu_tinymce'
          conf:
              label: "Si oui, préciser l’événement et le contexte : "
              required: false
        - id: "valuation_missions"
          type: collection
          conf:
              allow_add: true
              type: "to defined"
              allow_delete: true
              by_reference: false
              required: false
              label: "Evaluation de la mission permanente"
          child:
              - id: "mission_theme"
                type: "text"
                conf:
                    label: "Thème de la mission permanente"
                    required: false
              - id: "mission_state"
                type: "choice"
                conf:
                    label: "Etat"
                    required: true
                    choices: { n: "N", p: "P", r: "R", d: "D" }
                    expanded: true
                    multiple: false
              - id: "mission_comment"
                type: 'textarea'
                conf:
                    label: "Commentaires "
                    required: false
          number: 5
        - id: "valuation_goals"
          type: collection
          conf:
              allow_add: true
              type: "to defined"
              allow_delete: true
              by_reference: false
              required: false
              label: "Evaluation de l’atteinte des objectifs  :"
          child:
              - id: "goal_text"
                type: "text"
                conf:
                    label: "Rappel des objectifs"
                    required: false
              - id: "goal_metric"
                type: "number"
                conf:
                    label: "Indicateur de mesure"
                    required: false
              - id: "goal_deadline"
                type: "genemu_jquerydate"
                conf:
                    label: "Echéance"
                    required: false
                    attr:
                        class: 'datepicker'
                    widget: 'single_text'
                    format: 'dd/MM/yyyy'
              - id: "goal_state"
                type: "choice"
                conf:
                    label: "Etat"
                    required: true
                    choices: { n: "N", p: "P", r: "R", d: "D" }
                    expanded: true
                    multiple: false
              - id: "goal_comment"
                type: "textarea"
                conf:
                    label: "Commentaire(s)"
                    required: false
          number: 5
        - id: "general_valuation"
          type: "genemu_tinymce"
          conf:
              label: "Appréciation générale de la tenue du poste pour l’année écoulée :"
              required: false
        - id: "valuation_future_goals"
          type: collection
          conf:
              allow_add: true
              type: "to defined"
              allow_delete: true
              by_reference: false
              required: false
              label: "Evaluation de l’atteinte des objectifs  :"
          child:
              - id: "future_goal_text"
                type: "text"
                conf:
                    label: "Rappel des objectifs"
                    required: false
              - id: "future_goal_metric"
                type: "number"
                conf:
                    label: "Indicateur de mesure"
                    required: false
              - id: "future_goal_deadline"
                type: "genemu_jquerydate"
                conf:
                    label: "Echéance"
                    required: false
                    attr:
                        class: 'datepicker'
                    widget: 'single_text'
                    format: 'dd/MM/yyyy'
              - id: "future_goal_comment"
                type: "textarea"
                conf:
                    label: "Commentaires (risques, difficultés possibles, moyens nécessaires, priorités..)"
                    required: false
          number: 5






