name: "Entretien d'appréciation"
id: "valuation_meet"
fields:
    attr:
        - id: "valuation_bilan"
          type: "checkbox"
          conf:
              label: "L’année a été marquée par un événement significatif (mutation, évolution importante des responsabilités,  absence de longue durée, …)"
              required: true
              attr:
                  data-tab: "tab_2"
        - id: "valuation_context"
          type: "textarea"
          conf:
              label: "<i>Si oui, préciser l’événement et le contexte :</i>"
              required: false
              attr:
                  data-tab: "tab_2"
        - id: "valuation_missions"
          type: collection
          conf:
              allow_add: true
              type: "to defined"
              allow_delete: true
              by_reference: false
              required: false
              label: "Evaluation de la mission permanente : listez ci-dessous les principaux thèmes de la mission permanente et en évaluer leur réalisation :"
              attr:
                  data-tab: "tab_2"
          child:
              - id: "mission_theme"
                type: "text"
                conf:
                    label: "Thème de la mission permanente"
                    required: false
                    attr:
                        data-tab: "tab_2"
              - id: "mission_state"
                type: "choice"
                conf:
                    label: "Etat"
                    required: true
                    choices: { n: "N", p: "P", r: "R", d: "D" }
                    expanded: true
                    multiple: false
                    attr:
                        data-tab: "tab_2"
              - id: "mission_comment"
                type: 'textarea'
                conf:
                    label: "Commentaires "
                    required: false
                    attr:
                        data-tab: "tab_2"
                        class: "textarea-resize no-horizontal form-control"
          number: 5
        - id: "valuation_goals"
          type: collection
          conf:
              allow_add: true
              type: "to defined"
              allow_delete: true
              by_reference: false
              required: false
              label: "Evaluation de l’atteinte des objectifs  :"
              attr:
                  data-tab: "tab_2"
          child:
              - id: "goal_text"
                type: "text"
                conf:
                    label: "Rappel des objectifs"
                    required: false
                    attr:
                        data-tab: "tab_2"
              - id: "goal_metric"
                type: "number"
                conf:
                    label: "Indicateur de mesure"
                    required: false
                    attr:
                        data-tab: "tab_2"
              - id: "goal_deadline"
                type: "genemu_jquerydate"
                conf:
                    label: "Echéance"
                    required: false
                    attr:
                        class: 'datepicker'
                        data-tab: "tab_2"
                    widget: 'single_text'
                    format: 'dd/MM/yyyy'
              - id: "goal_state"
                type: "choice"
                conf:
                    label: "Etat"
                    required: true
                    choices: { n: "N", p: "P", r: "R", d: "D" }
                    expanded: true
                    multiple: false
                    attr:
                        data-tab: "tab_2"
              - id: "goal_comment"
                type: "textarea"
                conf:
                    label: "Commentaire(s)"
                    required: false
                    attr:
                        data-tab: "tab_2"
                        class: 'textarea-resize no-horizontal form-control'
          number: 5
        - id: "general_valuation"
          type: "genemu_tinymce"
          conf:
              label: "Appréciation générale de la tenue du poste pour l’année écoulée :"
              required: false
              attr:
                  data-tab: "tab_2"
        - id: "valuation_future_goals"
          type: collection
          conf:
              allow_add: true
              type: "to defined"
              allow_delete: true
              by_reference: false
              required: false
              label: "Nouveaux objectifs : déterminez les objectifs pour les 12 prochains mois par ordre d’importance (3 objectifs différents sont recommandés, 5 au maximum)."
              attr:
                  data-tab: "tab_3"
          child:
              - id: "future_goal_text"
                type: "text"
                conf:
                    label: "Rappel des objectifs"
                    required: false
                    attr:
                        data-tab: "tab_3"
              - id: "future_goal_metric"
                type: "number"
                conf:
                    label: "Indicateur de mesure"
                    required: false
                    attr:
                        data-tab: "tab_3"
              - id: "future_goal_deadline"
                type: "genemu_jquerydate"
                conf:
                    label: "Echéance"
                    required: false
                    attr:
                        class: 'datepicker'
                        data-tab: "tab_3"
                    widget: 'single_text'
                    format: 'dd/MM/yyyy'
              - id: "future_goal_comment"
                type: "textarea"
                conf:
                    label: "Commentaires (risques, difficultés possibles, moyens nécessaires, priorités..)"
                    required: false
                    attr:
                        data-tab: "tab_3"
                        class: 'textarea-resize no-horizontal form-control'
          number: 5
        - id: employee_obs
          type: "textarea"
          conf:
              label: "Observations éventuelles du salarié à l’issue de l’entretien (à remplir par le salarié)"
              required: false
              attr:
                  data-tab: "tab_4"
                  data-access: "assessed"






