<?php

namespace GeneratorBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use GeneratorBundle\Entity\OpusSheetType;

/**
 * OpusCampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpusCampaignRepository extends EntityRepository
{
    public function findLastInfoByType(OpusSheetType $type) {

        $qb = $this->createQueryBuilder('i')
            ->join("i.type", "t")
            ->where('t.id = :tid')
            ->andWhere('i.status = :active')
            ->andWhere('i.year = :datenow')
            ->setParameters(array('tid' => $type->getId(),
                "datenow" => date('Y'),
                'active' => 1))
            ->getQuery();


        return $qb->getSingleResult();
    }
}
