<?php

namespace GeneratorBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use GeneratorBundle\Entity\OpusJob;

/**
 * OpusJobRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpusJobRepository extends EntityRepository
{
    public function findOneByQuery(OpusJob $job)
    {
        $qb = $this->createQueryBuilder('j')
            ->where('j.id = :jid')
            ->setParameter('jid', $job->getId());

        return $qb;
    }
}
