<?php

namespace GeneratorBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OpusSheetTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpusSheetTypeRepository extends EntityRepository
{
}
