services:
    app_main.menu_builder:
        class: AppBundle\Menu\Builder

    app_main.menu.main:
        class: KnpMenuMenuItem
        factory_service: app_main.menu_builder
        factory_method: mainMenu
        arguments: ["@knp_menu.factory", "@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main } # L'alias est très important, c'est avec lui que vous appellerez votre menu dans la vue
    app_main.menu.user:
        class: KnpMenuMenuItem
        factory_service: app_main.menu_builder
        factory_method: userMenu
        arguments: ["@knp_menu.factory", "@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: user } # L'alias est très important, c'est avec lui que vous appellerez votre menu dans la vue
    app.excelbuilder:
        class: AppBundle\Service\ExcelBuilder
        calls:
            - [ setExcel, [ "@phpexcel" ] ]

#%param%
#@service