<?php

namespace FormGeneratorBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProfessionalAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionalAttributeRepository extends EntityRepository
{
}
