<?php

namespace FormGeneratorBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProfessionalMeetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionalMeetRepository extends EntityRepository
{
}
