<?php

namespace FormGeneratorBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ValuationAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValuationAttributeRepository extends EntityRepository
{
}
